name: Build PWA APK

on:
  workflow_dispatch:
    inputs:
      pwa_url:
        description: 'URL-ul PWA'
        required: true
        default: 'https://vivos-land.vercel.app'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

     - name: Init PWA
        run: printf "n\n$JAVA_HOME\n" | bubblewrap init --manifest=${{ github.event.inputs.pwa_url }}/manifest.json
      - name: Build APK
        run: bubblewrap build --skipPwaValidation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vivos-app
          path: '*.apk'
